"""Export rules to Great Expectations, pandera, SQL and a Markdown report."""
from __future__ import annotations

import json
from typing import Any, Iterable

from .rules import Rule


def _q(name: str) -> str:
    return '"' + name.replace('"', '""') + '"'


def _lit(v: Any) -> str:
    if isinstance(v, (int, float)):
        return repr(v)
    return "'" + str(v).replace("'", "''") + "'"


# ---------- Great Expectations ----------
def to_great_expectations(rules: Iterable[Rule], suite_name: str = "dq_rules_agent_suite") -> dict:
    exps = []
    for r in rules:
        meta = {"rule_id": r.rule_id, "severity": r.severity, "rationale": r.rationale}
        c, p = r.column, r.params
        e = None
        if r.check == "not_null":
            e = ("expect_column_values_to_not_be_null", {"column": c})
        elif r.check == "max_null_rate":
            e = ("expect_column_values_to_not_be_null", {"column": c, "mostly": round(1 - p["max_rate"], 4)})
        elif r.check == "unique":
            e = ("expect_column_values_to_be_unique", {"column": c})
        elif r.check == "between":
            kw = {"column": c}
            if p.get("min") is not None:
                kw["min_value"] = p["min"]
            if p.get("max") is not None:
                kw["max_value"] = p["max"]
            e = ("expect_column_values_to_be_between", kw)
        elif r.check == "in_set":
            e = ("expect_column_values_to_be_in_set", {"column": c, "value_set": p["values"]})
        elif r.check == "regex":
            e = ("expect_column_values_to_match_regex", {"column": c, "regex": p["pattern"]})
        elif r.check == "length":
            e = ("expect_column_value_lengths_to_be_between", {"column": c, "min_value": p["min"], "max_value": p["max"]})
        elif r.check == "type":
            m = {"integer": ["int", "int64", "Int64", "INTEGER", "BIGINT"],
                 "float": ["float", "float64", "Float64", "DOUBLE", "NUMERIC"],
                 "datetime": ["datetime64[ns]", "TIMESTAMP", "DATE"],
                 "boolean": ["bool", "boolean", "BOOLEAN"]}[p["kind"]]
            e = ("expect_column_values_to_be_in_type_list", {"column": c, "type_list": m})
        elif r.check == "row_count_between":
            e = ("expect_table_row_count_to_be_between", {"min_value": p.get("min"), "max_value": p.get("max")})
        elif r.check == "no_surrounding_whitespace":
            e = ("expect_column_values_to_not_match_regex", {"column": c, "regex": r"^\s|\s$"})
        elif r.check == "date_not_before":
            e = ("expect_column_values_to_be_between", {"column": c, "min_value": p["min"]})
        if e:
            exps.append({"expectation_type": e[0], "kwargs": e[1], "meta": meta})
    return {"expectation_suite_name": suite_name, "expectations": exps,
            "meta": {"generated_by": "dq-rules-agent"}}


# ---------- pandera ----------
def to_pandera(rules: Iterable[Rule], schema_name: str = "GeneratedSchema") -> str:
    rules = list(rules)
    cols: dict[str, list[Rule]] = {}
    for r in rules:
        if r.column:
            cols.setdefault(r.column, []).append(r)
    lines = [
        '"""Pandera schema generated by dq-rules-agent. Review before use."""',
        "import pandera.pandas as pa",
        "",
        f"{schema_name} = pa.DataFrameSchema(",
        "    {",
    ]
    for col, rs in cols.items():
        checks, nullable, unique = [], True, False
        for r in rs:
            p = r.params
            if r.check == "not_null":
                nullable = False
            elif r.check == "unique":
                unique = True
            elif r.check == "between":
                if p.get("min") is not None and p.get("max") is not None:
                    checks.append(f"pa.Check.in_range({p['min']!r}, {p['max']!r})")
                elif p.get("min") is not None:
                    checks.append(f"pa.Check.ge({p['min']!r})")
            elif r.check == "in_set":
                checks.append(f"pa.Check.isin({p['values']!r})")
            elif r.check == "regex":
                checks.append(f"pa.Check.str_matches({p['pattern']!r})")
            elif r.check == "length":
                checks.append(f"pa.Check.str_length({p['min']}, {p['max']})")
        cl = ", ".join(checks)
        lines.append(f"        {col!r}: pa.Column(checks=[{cl}], nullable={nullable}, unique={unique}, coerce=True),")
    lines += ["    },", "    strict=False,", ")", ""]
    return "\n".join(lines)


# ---------- SQL ----------
def to_sql(rules: Iterable[Rule], table: str = "my_table") -> str:
    """One query per rule. Each returns the number of violating rows (0 = pass)."""
    out = [f"-- Data quality checks generated by dq-rules-agent for {table}",
           "-- Each query returns failed_rows; 0 means the rule passes.", ""]
    t = table
    for r in rules:
        c, p = (_q(r.column) if r.column else None), r.params
        where = None
        if r.check == "not_null":
            where = f"{c} IS NULL"
        elif r.check == "between":
            parts = []
            if p.get("min") is not None:
                parts.append(f"{c} < {p['min']}")
            if p.get("max") is not None:
                parts.append(f"{c} > {p['max']}")
            where = " OR ".join(parts)
        elif r.check == "in_set":
            where = f"{c} IS NOT NULL AND {c} NOT IN ({', '.join(_lit(v) for v in p['values'])})"
        elif r.check == "regex":
            where = f"{c} IS NOT NULL AND NOT regexp_matches({c}, {_lit(p['pattern'])})"
        elif r.check == "length":
            where = f"length({c}) NOT BETWEEN {p['min']} AND {p['max']}"
        elif r.check == "no_surrounding_whitespace":
            where = f"{c} <> trim({c})"
        elif r.check == "date_not_after":
            where = f"TRY_CAST({c} AS DATE) > CURRENT_DATE"
        elif r.check == "date_not_before":
            where = f"TRY_CAST({c} AS DATE) < DATE {_lit(p['min'])}"
        out.append(f"-- {r.rule_id} [{r.severity}] {r.rationale}")
        if where:
            out.append(f"SELECT '{r.rule_id}' AS rule_id, COUNT(*) AS failed_rows FROM {t} WHERE {where};")
        elif r.check == "unique":
            out.append(f"SELECT '{r.rule_id}' AS rule_id, COALESCE(SUM(n), 0) AS failed_rows FROM "
                       f"(SELECT COUNT(*) AS n FROM {t} WHERE {c} IS NOT NULL GROUP BY {c} HAVING COUNT(*) > 1) d;")
        elif r.check == "max_null_rate":
            out.append(f"SELECT '{r.rule_id}' AS rule_id, CASE WHEN AVG(CASE WHEN {c} IS NULL THEN 1.0 ELSE 0 END) "
                       f"> {p['max_rate']} THEN 1 ELSE 0 END AS failed_rows FROM {t};")
        elif r.check == "row_count_between":
            out.append(f"SELECT '{r.rule_id}' AS rule_id, CASE WHEN COUNT(*) BETWEEN {p['min']} AND {p['max']} "
                       f"THEN 0 ELSE 1 END AS failed_rows FROM {t};")
        elif r.check == "no_duplicate_rows":
            out.append(f"SELECT '{r.rule_id}' AS rule_id, COUNT(*) - (SELECT COUNT(*) FROM (SELECT DISTINCT * FROM {t}) d) "
                       f"AS failed_rows FROM {t};")
        elif r.check == "type":
            cast = {"integer": "BIGINT", "float": "DOUBLE", "datetime": "TIMESTAMP", "boolean": "BOOLEAN"}[p["kind"]]
            out.append(f"SELECT '{r.rule_id}' AS rule_id, COUNT(*) AS failed_rows FROM {t} "
                       f"WHERE {c} IS NOT NULL AND TRY_CAST({c} AS {cast}) IS NULL;")
        out.append("")
    return "\n".join(out)


# ---------- report ----------
def to_markdown(profile: dict, rules: Iterable[Rule], results: list[dict] | None = None) -> str:
    rules = list(rules)
    res = {r["rule_id"]: r for r in (results or [])}
    lines = ["# Data quality rules report", "",
             f"Rows: {profile['row_count']} | Columns: {profile['column_count']} | "
             f"Duplicate rows: {profile['duplicate_rows']} | Rules suggested: {len(rules)}", "",
             "## Column profile", "",
             "| column | type | null % | distinct | range / top pattern |", "|---|---|---|---|---|"]
    for c in profile["columns"]:
        extra = ""
        if "min" in c:
            extra = f"{c['min']} to {c['max']}"
        elif c.get("patterns"):
            k, v = max(c["patterns"].items(), key=lambda kv: kv[1])
            extra = f"{k} ({v:.0%})"
        lines.append(f"| {c['name']} | {c['kind']} | {c['null_rate']:.1%} | {c['distinct']} | {extra} |")
    lines += ["", "## Suggested rules", "",
              "| rule | severity | confidence | why | result |", "|---|---|---|---|---|"]
    for r in rules:
        rr = res.get(r.rule_id)
        status = "" if rr is None else ("pass" if rr["passed"] else f"FAIL ({rr['failed_rows']} rows)")
        lines.append(f"| `{r.rule_id}` | {r.severity} | {r.confidence:.0%} | {r.rationale} | {status} |")
    return "\n".join(lines) + "\n"


def to_json(rules: Iterable[Rule]) -> str:
    return json.dumps([r.to_dict() for r in rules], indent=2, default=str)
