-- Data quality checks generated by dq-rules-agent for customers
-- Each query returns failed_rows; 0 means the rule passes.

-- table.row_count [warning] Current load has 500 rows; flag loads under half or over double that.
SELECT 'table.row_count' AS rule_id, CASE WHEN COUNT(*) BETWEEN 250 AND 1000 THEN 0 ELSE 1 END AS failed_rows FROM customers;

-- table.no_duplicate_rows [error] 0 fully duplicated rows found.
SELECT 'table.no_duplicate_rows' AS rule_id, COUNT(*) - (SELECT COUNT(*) FROM (SELECT DISTINCT * FROM customers) d) AS failed_rows FROM customers;

-- customer_id.not_null [error] 0 of 500 rows are null.
SELECT 'customer_id.not_null' AS rule_id, COUNT(*) AS failed_rows FROM customers WHERE "customer_id" IS NULL;

-- customer_id.unique [error] All 500 non-null values are distinct and the name looks like a key.
SELECT 'customer_id.unique' AS rule_id, COALESCE(SUM(n), 0) AS failed_rows FROM (SELECT COUNT(*) AS n FROM customers WHERE "customer_id" IS NOT NULL GROUP BY "customer_id" HAVING COUNT(*) > 1) d;

-- customer_id.pattern_alnum_code [error] 100.0% of values match the alnum_code pattern.
SELECT 'customer_id.pattern_alnum_code' AS rule_id, COUNT(*) AS failed_rows FROM customers WHERE "customer_id" IS NOT NULL AND NOT regexp_matches("customer_id", '^[A-Z]{2,5}-?\d{2,8}$');

-- customer_id.fixed_length [warning] Every value is exactly 11 characters.
SELECT 'customer_id.fixed_length' AS rule_id, COUNT(*) AS failed_rows FROM customers WHERE length("customer_id") NOT BETWEEN 11 AND 11;

-- email.not_null [error] 0 of 500 rows are null.
SELECT 'email.not_null' AS rule_id, COUNT(*) AS failed_rows FROM customers WHERE "email" IS NULL;

-- email.unique [error] All 500 non-null values are distinct.
SELECT 'email.unique' AS rule_id, COALESCE(SUM(n), 0) AS failed_rows FROM (SELECT COUNT(*) AS n FROM customers WHERE "email" IS NOT NULL GROUP BY "email" HAVING COUNT(*) > 1) d;

-- email.pattern_email [error] 100.0% of values match the email pattern.
SELECT 'email.pattern_email' AS rule_id, COUNT(*) AS failed_rows FROM customers WHERE "email" IS NOT NULL AND NOT regexp_matches("email", '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$');

-- signup_date.not_null [error] 0 of 500 rows are null.
SELECT 'signup_date.not_null' AS rule_id, COUNT(*) AS failed_rows FROM customers WHERE "signup_date" IS NULL;

-- signup_date.type [error] Profiler inferred 'datetime' for all non-null values.
SELECT 'signup_date.type' AS rule_id, COUNT(*) AS failed_rows FROM customers WHERE "signup_date" IS NOT NULL AND TRY_CAST("signup_date" AS TIMESTAMP) IS NULL;

-- signup_date.not_in_future [error] Latest value is 2025-05-14; no future dates seen.
SELECT 'signup_date.not_in_future' AS rule_id, COUNT(*) AS failed_rows FROM customers WHERE TRY_CAST("signup_date" AS DATE) > CURRENT_DATE;

-- signup_date.date_floor [warning] Earliest value is 2024-01-01.
SELECT 'signup_date.date_floor' AS rule_id, COUNT(*) AS failed_rows FROM customers WHERE TRY_CAST("signup_date" AS DATE) < DATE '2024-01-01';

-- city.not_null [error] 0 of 500 rows are null.
SELECT 'city.not_null' AS rule_id, COUNT(*) AS failed_rows FROM customers WHERE "city" IS NULL;

-- city.allowed_values [error] Only 6 distinct values in 500 rows; treat as a closed list.
SELECT 'city.allowed_values' AS rule_id, COUNT(*) AS failed_rows FROM customers WHERE "city" IS NOT NULL AND "city" NOT IN ('Brampton', 'Markham', 'Mississauga', 'Oakville', 'Toronto', 'Vaughan');

-- city.length [warning] Lengths range from 7 to 11.
SELECT 'city.length' AS rule_id, COUNT(*) AS failed_rows FROM customers WHERE length("city") NOT BETWEEN 7 AND 11;

-- postal_code.not_null [error] 0 of 500 rows are null.
SELECT 'postal_code.not_null' AS rule_id, COUNT(*) AS failed_rows FROM customers WHERE "postal_code" IS NULL;

-- postal_code.unique [error] All 500 non-null values are distinct and the name looks like a key.
SELECT 'postal_code.unique' AS rule_id, COALESCE(SUM(n), 0) AS failed_rows FROM (SELECT COUNT(*) AS n FROM customers WHERE "postal_code" IS NOT NULL GROUP BY "postal_code" HAVING COUNT(*) > 1) d;

-- postal_code.pattern_ca_postal_code [error] 100.0% of values match the ca_postal_code pattern.
SELECT 'postal_code.pattern_ca_postal_code' AS rule_id, COUNT(*) AS failed_rows FROM customers WHERE "postal_code" IS NOT NULL AND NOT regexp_matches("postal_code", '^[A-Za-z]\d[A-Za-z][ -]?\d[A-Za-z]\d$');

-- postal_code.fixed_length [warning] Every value is exactly 7 characters.
SELECT 'postal_code.fixed_length' AS rule_id, COUNT(*) AS failed_rows FROM customers WHERE length("postal_code") NOT BETWEEN 7 AND 7;

-- plan.not_null [error] 0 of 500 rows are null.
SELECT 'plan.not_null' AS rule_id, COUNT(*) AS failed_rows FROM customers WHERE "plan" IS NULL;

-- plan.allowed_values [error] Only 3 distinct values in 500 rows; treat as a closed list.
SELECT 'plan.allowed_values' AS rule_id, COUNT(*) AS failed_rows FROM customers WHERE "plan" IS NOT NULL AND "plan" NOT IN ('basic', 'plus', 'pro');

-- plan.length [warning] Lengths range from 3 to 5.
SELECT 'plan.length' AS rule_id, COUNT(*) AS failed_rows FROM customers WHERE length("plan") NOT BETWEEN 3 AND 5;

-- monthly_spend.max_null_rate [warning] 2.4% null today; alert if it rises above 4%.
SELECT 'monthly_spend.max_null_rate' AS rule_id, CASE WHEN AVG(CASE WHEN "monthly_spend" IS NULL THEN 1.0 ELSE 0 END) > 0.04 THEN 1 ELSE 0 END AS failed_rows FROM customers;

-- monthly_spend.type [error] Profiler inferred 'float' for all non-null values.
SELECT 'monthly_spend.type' AS rule_id, COUNT(*) AS failed_rows FROM customers WHERE "monthly_spend" IS NOT NULL AND TRY_CAST("monthly_spend" AS DOUBLE) IS NULL;

-- monthly_spend.non_negative [error] No negative values across 488 rows (min 3.5).
SELECT 'monthly_spend.non_negative' AS rule_id, COUNT(*) AS failed_rows FROM customers WHERE "monthly_spend" < 0;

-- monthly_spend.expected_range [warning] Observed 3.5 to 182.84 (median 55.16, 9 IQR outliers). Values outside 0 to 300 need review.
SELECT 'monthly_spend.expected_range' AS rule_id, COUNT(*) AS failed_rows FROM customers WHERE "monthly_spend" < 0.0 OR "monthly_spend" > 300;

-- orders_last_90d.not_null [error] 0 of 500 rows are null.
SELECT 'orders_last_90d.not_null' AS rule_id, COUNT(*) AS failed_rows FROM customers WHERE "orders_last_90d" IS NULL;

-- orders_last_90d.type [error] Profiler inferred 'integer' for all non-null values.
SELECT 'orders_last_90d.type' AS rule_id, COUNT(*) AS failed_rows FROM customers WHERE "orders_last_90d" IS NOT NULL AND TRY_CAST("orders_last_90d" AS BIGINT) IS NULL;

-- orders_last_90d.non_negative [error] No negative values across 500 rows (min 0).
SELECT 'orders_last_90d.non_negative' AS rule_id, COUNT(*) AS failed_rows FROM customers WHERE "orders_last_90d" < 0;

-- orders_last_90d.expected_range [warning] Observed 0 to 15 (median 6, 9 IQR outliers). Values outside 0 to 20 need review.
SELECT 'orders_last_90d.expected_range' AS rule_id, COUNT(*) AS failed_rows FROM customers WHERE "orders_last_90d" < 0.0 OR "orders_last_90d" > 20;

-- is_active.not_null [error] 0 of 500 rows are null.
SELECT 'is_active.not_null' AS rule_id, COUNT(*) AS failed_rows FROM customers WHERE "is_active" IS NULL;

-- is_active.type [error] Profiler inferred 'boolean' for all non-null values.
SELECT 'is_active.type' AS rule_id, COUNT(*) AS failed_rows FROM customers WHERE "is_active" IS NOT NULL AND TRY_CAST("is_active" AS BOOLEAN) IS NULL;
