"""Pandera schema generated by dq-rules-agent. Review before use."""
import pandera.pandas as pa

GeneratedSchema = pa.DataFrameSchema(
    {
        'customer_id': pa.Column(checks=[pa.Check.str_matches('^[A-Z]{2,5}-?\\d{2,8}$'), pa.Check.str_length(11, 11)], nullable=False, unique=True, coerce=True),
        'email': pa.Column(checks=[pa.Check.str_matches('^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$')], nullable=False, unique=True, coerce=True),
        'signup_date': pa.Column(checks=[], nullable=False, unique=False, coerce=True),
        'city': pa.Column(checks=[pa.Check.isin(['Brampton', 'Markham', 'Mississauga', 'Oakville', 'Toronto', 'Vaughan']), pa.Check.str_length(7, 11)], nullable=False, unique=False, coerce=True),
        'postal_code': pa.Column(checks=[pa.Check.str_matches('^[A-Za-z]\\d[A-Za-z][ -]?\\d[A-Za-z]\\d$'), pa.Check.str_length(7, 7)], nullable=False, unique=True, coerce=True),
        'plan': pa.Column(checks=[pa.Check.isin(['basic', 'plus', 'pro']), pa.Check.str_length(3, 5)], nullable=False, unique=False, coerce=True),
        'monthly_spend': pa.Column(checks=[pa.Check.ge(0), pa.Check.in_range(0.0, 300)], nullable=True, unique=False, coerce=True),
        'orders_last_90d': pa.Column(checks=[pa.Check.ge(0), pa.Check.in_range(0.0, 20)], nullable=False, unique=False, coerce=True),
        'is_active': pa.Column(checks=[], nullable=False, unique=False, coerce=True),
    },
    strict=False,
)
